### ISSUE TITLE
Custom Pref Buttons are not working

### ISSUE THREAD

**Issue by tasomaniac** [saik0/UnifiedPreference#3]
Hi today I tried to integrate your lib. It supposed to be easy but it is not.
Here is the problem.

My pref_headers.xml

<preference-headers xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:unified="http://schemas.android.com/apk/res-auto" >

```
<header
    unified:fragment="com.tasomaniac.hdfilmizle.preference.GeneralPreferenceFragment"
    unified:title="@string/settings"
    unified:preferenceRes="@xml/pref_general" />
<header
    unified:fragment="com.tasomaniac.hdfilmizle.preference.OnbellekPreferenceFragment"
    unified:title="Önbellek Ayarları"
    unified:preferenceRes="@xml/pref_onbellek" />
```

</preference-headers>

pref_onbellek.xml is here:

<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android">

```
    <CheckBoxPreference
        android:summary="@string/pref_summary_cache"
        android:title="@string/pref_title_cache_flag"
        android:key="@string/pref_key_flag_cache"
        android:defaultValue="true" />
     <Preference
        android:title="@string/pref_title_erasecache_flag"
        android:key="erasecache_flag" />
```

</PreferenceScreen>

Here I have <Preference> item.
In OnbellekPreferenceFragment.java I am calling it like below

@Override
        public void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);

```
        Preference customPref = (Preference) findPreference("erasecache_flag");
        customPref.setOnPreferenceClickListener(new OnPreferenceClickListener() {

            public boolean onPreferenceClick(Preference preference) {
                Toast.makeText(getActivity().getApplicationContext(),"Önbellek Silindi!",Toast.LENGTH_LONG).show();


                    new Thread(new Runnable() {
                        public void run() {
                            new ImageLoader(getActivity().getApplicationContext()).clearCache();
                        }
                    }).start();
                    return true;

            }
        });
    }
```

The problem is that it is not working. Actually I had a break point before super.onCreate() function. The breakpoint was not called at all. What can be a problem? 
When I supply an intent it is working.

**Comment by saik0** [comment]
The library uses the deprecated pre-API 11 methods for small screens and old devices, and the "modern" methods when the device's bool ref `com.android.internal.R.bool.preferences_prefer_dual_pane` is `true`. This means either the `PreferenceActivity` or the `PreferenceFragment` contains a `PreferenceScreen` and `PreferenceManager`.

I wrote [a gist to demonstrating how to to find preferences](https://gist.github.com/4073835) a while ago that deals with either case.

**Comment by tasomaniac** [comment]
Ok what does that mean? How do I make the custom buttons work?

**Comment by saik0** [comment]
Did you look at the gist? You need to:
- Call your code from the activity from `onPostCreate` and only if `isSinglePane()`
- Call your code from the relevant fragment `onCreate`

**Comment by tasomaniac** [comment]
Ok thank you very much.
But you should put this gist on your main page. Or you can put it as an
example in the demo.

Thank you very much for the lib.

## 

std

http://tasomaniac.com http://card.ly/taso
http://home.ku.edu.tr/~sdane

**Comment by saik0** [comment]
No problem, closing the issue.

**Comment by bostone** [comment]
I think you should remove restrictions other than OS version

**Comment by saik0** [comment]
@bostone Can you be more specific?

**Comment by bostone** [comment]
Sure, when I'm on Honeycomb+ why use legacy preferences at all? I think your isSinglePane() should be isLegacy() and check only for OS version. Also if I understand this right - on older devices no logic placed into Fragments will be executed since these are direct descendants of `android.preference.PreferenceFragment`. I think you should at least state that in your intro to the lib
