### ISSUE TITLE
Fragment code is completely ignored

### ISSUE THREAD

**Issue by bostone** [saik0/UnifiedPreference#4]
I have a very simple setup following your demo project

``` xml
<preference-headers xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:unified="http://schemas.android.com/apk/res/bostone.android.jobrio" >
    <header
        unified:fragment="bostone.android.jobrio.JobrioPreferenceActivity$AccountsFragment"
        unified:title="@string/pref_header_general"
        unified:preferenceRes="@xml/pref_general" />
</preference-headers>
```

pref_general.xml

``` xml
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android" >
    <CheckBoxPreference
        android:defaultValue="false"
        android:key="linkedin_login"
        android:summary="@string/pref_description_linkedin_account"
        android:title="@string/pref_title_linkedin_account" />
</PreferenceScreen>
```

And the java code

``` java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        setHeaderRes(R.xml.pref_headers);
        setSharedPreferencesName(getApplicationContext().getPackageName());
        setSharedPreferencesMode(Context.MODE_PRIVATE);
        super.onCreate(savedInstanceState);
        final ActionBar ab = getSupportActionBar();
        ab.setDisplayHomeAsUpEnabled(true);
    }

    public static class AccountsFragment extends UnifiedPreferenceFragment {

        @Override
        public void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
        }

        @Override
        public void onAttach(Activity activity) {
            super.onAttach(activity);
        }

    }
```

Preferences screen comes up just fine and checkbox property acts appropriately. What puzzle me is that `unified:fragment="bostone.android.jobrio.JobrioPreferenceActivity$AccountsFragment"` is seemingly ignored and in fact I can put any gibberish as fragment value and it will not generate any errors. As far as AccountsFragment goes - its onCreate and onAttach methods are never called.

I must be doing something wrong here?

Thanks,

Bo Stone

**Comment by saik0** [comment]
You should be getting a NoClassDefFound error. Are you building with Eclipse?

**Comment by bostone** [comment]
Yes sir. Like I said it has no effect

**Comment by saik0** [comment]
Please try closing the projects, then quit eclipse. Launch, re-open and clean the library and your project.

**Comment by bostone** [comment]
Same thing

**Comment by bostone** [comment]
Is there anything special that needs to go into manifest file? I just have a plain simple Activity definition

**Comment by saik0** [comment]
> Is there anything special that needs to go into manifest file? I just have a plain simple Activity definition

No. I am not able to replicate this. Your snippet should work fine, and a bad value for `unified:fragment` should produce a NoClassDefFound exception. I suspect there is a bug or configuration problem in the build system.

**Comment by saik0** [comment]
Here is a quick test project I setup using your samples. It also contains the apk that compiled and runs OK. Sorry I cant be of more help.

Edit: Forgot the link!
http://dropbox.saik0.net/preferencetest.zip

**Comment by bostone** [comment]
I run the code and I have absolutely the same effect. Runs fine, change unified:fragment="foo", clean, run, no error. Change back - AccountFragments.onCreate is never accessed. I step through your code and I think the problem is that when isSinglePane  returns true then fragments are simply ignored. So when I place some logic into fragment - it will never be picked up

**Comment by saik0** [comment]
Take a look at #3

**Comment by saik0** [comment]
This is a separate issue. Lets continue the discussion on issue #8.

While we're here though, some history: The initial release of the lib was only a "librarized" port of ADT SettingsActivity template because it was quite a bit of code for a minimally useful PreferenceActivity, and reusing the template was not DRY enough. There's still some weirdness from the template to cast off, pull requests welcome.

Edit: wrong issue number -_-

**Comment by vmihalachi** [comment]
Hi, the bug still persist. How can i fix it?
